#!/bin/bash
cat << "EOF" > /etc/motd.tail
  _                 _        ___ _               _   
 | |   ___ _ _  ___| |_  _  | _ \ |__ _ _ _  ___| |_ 
 | |__/ _ \ ' \/ -_) | || | |  _/ / _` | ' \/ -_)  _|
 |____\___/_||_\___|_|\_, | |_| |_\__,_|_||_\___|\__|
                      |__/                           
EOF
rm /etc/update-motd.d/98-cloudguest
rm /etc/update-motd.d/51_update-motd
rm /etc/update-motd.d/10-help-text
rm /etc/update-motd.d/50-landscape-sysinfo
