#!/bin/bash
#Add a deploy user with keys to our github Chef repo
useradd -m -G admin deploy -s /bin/bash
mkdir -p /home/deploy/.ssh
cat << "EOF" > /home/deploy/.ssh/id_rsa
-----BEGIN RSA PRIVATE KEY-----
Secret
-----END RSA PRIVATE KEY-----
EOF
chown -R deploy:deploy /home/deploy/.ssh
chmod 700 /home/deploy/.ssh
chmod 400 /home/deploy/.ssh/id_rsa
#SSH settings
echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
